language: go
go:
- 1.13
env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: d5fp3o23/hZeiqdTuxQp9SHJONJMOUo6swATVApZwshKZ5sIR0kwwA89eyAMZHoTlgn2uOku/wIVdLkDweeTb3KZLquXYkSFyFnzaoCrlDpvsyELFr+SAdVxqQYOE4Qv4GxxFvE1DxxpjA8Sh132vVzUxywM5nESaxqgI8bR9nTifkVitA0TKSMkMoT2TErdO3goYpon0LMFGqJAM45Q2qJZaj/hKR3fj3601ELW0nI0zICBjThu6xrCzAPp1musAbZF67cWMQdOzMzeDvX35uZVBuwQt6MQIMWFSCSluYZFlbD2icFN//6S9J2Ti8Bobc+dT+jlpy4sPJRUAfxelszq+9ju1O2CVUjZ91KxMGkrEUKIUcmmqhWwyb57TBeowGnf2vIbwldMRutHtwZJyOKN+2Sw+19GBLcBToHR3u22OOmMZYHZLSjEvWyb+Cev0Nz1rAIqIwxdrvzDgrf7318dafn6LTrCwVTF9gYYWZWyM0O+lUBY1Vj6yu7usNRkF9vVF/leObExrHQap9/LhJebIJcIepoyQ/KyYYcNMyGOsci3c2FetG8Bv/KrbN4SA19IPvdDp5yClfdPJU7gw5Gshr0iKK5MBCcH1CzfWQFWqNNQO5NOgt7eySZtq1NDLMqwjyl+rh60c97ffvR1NvJ+/BzMLMF1696z72/TNM4=
  file: bin/dockercat-mac-amd64
  on:
    repo: nuknal/dockercat
  skip_cleanup: 'true'
notifications:
  email: true
